#!/usr/bin/env bash
# Generate each platform's pre-commit hook AND CI workflow from its spoke.manifest.
#
# Both run exactly the native validators the manifest declares, so the check a spoke runs
# on itself, the check CI runs, and the check the hub runs before exporting cannot
# disagree. Re-run this after changing any native_validator line, then --push.
#
# The hook is a fast local convenience and depends on `git config core.hooksPath`, which
# does not survive a fresh clone. CI is the guarantee that does not depend on any local
# state: a clone with no hooks configured still cannot land a broken tree unnoticed.
#
# CI runs only the `sh ...` validators — the repo's own portable checkers. Validators that
# shell out to a proprietary CLI (`claude plugin validate`, `agy plugin validate`) are not
# installable on a runner, so they stay local and pre-commit only. That is stated in the
# generated workflow rather than papered over.

set -uo pipefail
hub_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)

# A native_validator value is embedded into generated shell and YAML that later EXECUTES.
# That makes it code, not data: a value carrying a quote or a semicolon would break out of
# the quoting and run whatever followed, on a maintainer's machine at every commit — while
# the payload sat in a manifest and the dangerous artifact appeared only in generated
# output nobody re-reads. Same posture as path_is_sane in sync-spokes.sh: validate first,
# then quote anyway.
validator_is_sane() {
  case $1 in
    '' ) return 1 ;;
    *[!A-Za-z0-9\ ._/=:-]* ) return 1 ;;
  esac
  return 0
}

shell_quote() {
  # Belt and braces even after the allowlist: the standard '"'"' transform.
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\"'\"'/g")"
}

for manifest in "$hub_root"/platforms/*/spoke.manifest; do
  platform=$(basename "$(dirname "$manifest")")
  hooks_dir="$hub_root/platforms/$platform/scripts/hooks"
  mkdir -p "$hooks_dir"
  {
    cat <<'HEAD'
#!/usr/bin/env bash
# Runs this repository's own native validators before every commit.
#
# Generated by agent-advisor (scripts/gen-spoke-checks.sh) from this platform's
# spoke.manifest. Do not edit here — edit the manifest in the hub and regenerate, or the
# next sync will overwrite it.
#
# Enable once per clone:   git config core.hooksPath scripts/hooks
# Bypass deliberately:     git commit --no-verify

cd "$(git rev-parse --show-toplevel)" || exit 1
status=0

run() {
  if out=$(sh -c "$1" 2>&1); then
    printf 'ok   %s\n' "$1"
  else
    printf 'FAIL %s\n' "$1" >&2
    printf '%s\n' "$out" | tail -15 | sed 's/^/     /' >&2
    status=1
  fi
}

HEAD
    sed -n 's/^native_validator=//p' "$manifest" | while IFS= read -r v; do
      [ -n "$v" ] || continue
      if ! validator_is_sane "$v"; then
        printf 'ERROR: %s: native_validator is not a plain command: %s\n' "$platform" "$v" >&2
        printf '       Allowed characters: letters, digits, space . _ / = : -\n' >&2
        exit 3
      fi
      printf 'run %s\n' "$(shell_quote "$v")"
    done || exit 3
    cat <<'TAIL'

if [ "$status" -ne 0 ]; then
  printf '\npre-commit: validation failed. Commit blocked.\n' >&2
  printf 'Fix the failure above, or use --no-verify if you mean to commit it broken.\n' >&2
fi
exit "$status"
TAIL
  } > "$hooks_dir/pre-commit"
  chmod +x "$hooks_dir/pre-commit"

  wf_dir="$hub_root/platforms/$platform/.github/workflows"
  mkdir -p "$wf_dir"
  {
    cat <<'WFHEAD'
# Generated by agent-advisor (scripts/gen-spoke-checks.sh) from this repo's entry in the
# hub's spoke.manifest. Do not edit here — edit the manifest and regenerate.
#
# This is the backstop for the pre-commit hook. `git config core.hooksPath scripts/hooks`
# is local config and does not survive a clone, so a fresh clone has no hook. CI does not
# care: it runs the same validators on every push and pull request regardless.
name: validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show what is being checked
        run: |
          echo "Running this repository's own native validators."
          echo "CLI-dependent validators are skipped here; see the hub's gen-spoke-checks.sh."
WFHEAD
    sed -n 's/^native_validator=//p' "$manifest" | while IFS= read -r v; do
      if ! validator_is_sane "$v"; then
        printf 'ERROR: %s: native_validator is not a plain command: %s\n' "$platform" "$v" >&2
        exit 3
      fi
      case "$v" in
        sh\ *|bash\ *)
          # Block scalar with the command on its own line: never interpolated into a YAML
          # scalar where a quote or colon could restructure the document.
          printf '      - name: native validator\n        run: |\n          %s\n' "$v"
          ;;
        *)
          printf '      # skipped in CI (needs a CLI that cannot be installed on a runner): %s\n' "$v"
          ;;
      esac
    done
  } > "$wf_dir/validate.yml"
  printf '  %-12s %s\n' "$platform" "$(sed -n 's/^native_validator=/runs: /p' "$manifest" | tr '\n' ' ')"
done
