#!/usr/bin/env bash
# Generate each platform's pre-commit hook from its spoke.manifest.
#
# The hook runs exactly the native validators the manifest declares, so the check a spoke
# runs on itself and the check the hub runs before exporting to it cannot disagree. Re-run
# this after changing any native_validator line, then --push.

set -uo pipefail
hub_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)

for manifest in "$hub_root"/platforms/*/spoke.manifest; do
  platform=$(basename "$(dirname "$manifest")")
  hooks_dir="$hub_root/platforms/$platform/scripts/hooks"
  mkdir -p "$hooks_dir"
  {
    cat <<'HEAD'
#!/usr/bin/env bash
# Runs this repository's own native validators before every commit.
#
# Generated by agent-advisor (scripts/gen-spoke-hooks.sh) from this platform's
# spoke.manifest. Do not edit here — edit the manifest in the hub and regenerate, or the
# next sync will overwrite it.
#
# Enable once per clone:   git config core.hooksPath scripts/hooks
# Bypass deliberately:     git commit --no-verify

cd "$(git rev-parse --show-toplevel)" || exit 1
status=0

run() {
  if out=$(sh -c "$1" 2>&1); then
    printf 'ok   %s\n' "$1"
  else
    printf 'FAIL %s\n' "$1" >&2
    printf '%s\n' "$out" | tail -15 | sed 's/^/     /' >&2
    status=1
  fi
}

HEAD
    sed -n 's/^native_validator=//p' "$manifest" | while IFS= read -r v; do
      [ -n "$v" ] && printf 'run %s\n' "'$v'"
    done
    cat <<'TAIL'

if [ "$status" -ne 0 ]; then
  printf '\npre-commit: validation failed. Commit blocked.\n' >&2
  printf 'Fix the failure above, or use --no-verify if you mean to commit it broken.\n' >&2
fi
exit "$status"
TAIL
  } > "$hooks_dir/pre-commit"
  chmod +x "$hooks_dir/pre-commit"
  printf '  %-12s %s\n' "$platform" "$(sed -n 's/^native_validator=/runs: /p' "$manifest" | tr '\n' ' ')"
done
